spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

egrant.cors.allowed-origins=*
egrant.mail.enabled=false

logging.level.az.aztu.egrant=DEBUG
logging.level.org.springframework.modulith=INFO
