spring.jpa.show-sql=false

# In prod these MUST be provided via env.
egrant.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://e-grant.aztu.edu.az}
egrant.mail.enabled=true

logging.level.az.aztu.egrant=INFO
